import recursionBinaryTree from './binaryTree/binaryTreeByRecursion';
console.log(recursionBinaryTree,'recursionBinaryTree')
const treeByRecursion= recursionBinaryTree.createBinaryTreeByRecursion([3,2,9,null,null,10,null,null,8,null,4])
console.log('通过递归生成的二叉树-tree:',treeByRecursion)
console.log('前序遍历:')
recursionBinaryTree.preOrderTraveralByRecursion(treeByRecursion)
console.log('中序遍历:')
recursionBinaryTree.inOrderTraveralByRecursion(treeByRecursion)
console.log('后序遍历:')
recursionBinaryTree.postOrderTraveralByRecursion(treeByRecursion)